### ISSUE TITLE
Move for loops to own functions with sensible names.

### ISSUE THREAD

**Issue by wolski** [protViz/deisotoper#47] opened 2017-11-14 12:41 UTC
https://github.com/protViz/deisotoper/blob/44ae82964c84eeef0ce3f5aecabca8e9e43d8bed/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Deisotoper.java#L43

**Comment by LukeCaruzo** [comment] 2017-11-15 10:30
Duplicate of #57

**Closed by LukeCaruzo** 2017-11-15 10:30 UTC
